name: CI/CD

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      # Cache npm dependencies
      # - name: Cache npm dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-


      # # Install npm dependencies
      # - name: Install dependencies
      #   run: |
      #     cd app && npm ci


      # # Cache Docker layers
      # - name: Cache Docker layers
      #   uses: actions/cache@v3
      #   with:
      #     path: /tmp/.docker-cache
      #     key: ${{ runner.os }}-docker-${{ hashFiles('docker-compose.prod.yml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-docker-


      # - name: Download Docker
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y docker-compose


      # # Build and run the Docker containers
      # - name: Build client app
      #   run: |
      #     docker-compose -f docker-compose.prod.yml up --build -d --no-cache


      # # Run client tests (если они есть)
      # # - name: Run client tests
      # #   run: |
      # #     docker exec -w /app ==client-container== npm run test


      # # Stop and remove Docker containers after tests
      # - name: Stop and remove containers
      #   run: docker-compose -f docker-compose.prod.yml down

      - name: Build App
        working-directory: ./app
        run: npm i && npm run build


  deploy:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        working-directory: ./app/dist
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        working-directory: ./app/dist
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: ./app/dist
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}


      - name: Deploy Project Artifacts to Vercel
        working-directory: ./app/dist
        if: github.ref == 'refs/heads/main' && success()
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
